name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile project
        run: mvn clean compile

  integration_test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Integration Tests
        run: mvn verify -DskipUnitTests=true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: target/failsafe-reports/*.xml

  spotbugs:
    name: SpotBugs Analysis
    runs-on: ubuntu-latest
    needs: integration_test
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run SpotBugs
        run: mvn spotbugs:spotbugs

      - name: Upload SpotBugs report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-report
          path: target/spotbugsXml.xml

  owasp_dependency_check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    needs: spotbugs
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check
        continue-on-error: true  # allow_failure equivalent

  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: owasp_dependency_check
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        run: ./scripts/deploy.sh
